enable_pr_creation: true
enable_sparse_checkout: true
github_token: ''
history_branch: master
history_repo: https://github.com/HL7/fhir-ig-history-template
registry_pr_target_branch: master
#source_branch: main
source_dir: ''
#source_repo: https://github.com/costateixeira/smart-dak-pnc
sparse_dirs:
- templates
- assets
webroot_branch: main
webroot_pr_target_branch: main
webroot_repo: https://github.com/costateixeira/smart-html
