enable_pr_creation: true
enable_sparse_checkout: false
github_token: ''
history_branch: master
history_repo: https://github.com/HL7/fhir-ig-history-template
registry_pr_target_branch: master
source_branch: v0.9.9_releaseCandidate
source_dir: ''
source_repo: https://github.com/WorldHealthOrganization/smart-dak-pnc
sparse_dirs:
- templates
- assets
webroot_branch: main
webroot_pr_target_branch: main
webroot_repo: https://github.com/WorldHealthOrganization/smart-html
