name: Reusable Release IG & Publish to sitepreview

on:
  workflow_call:
    inputs:
      branch:
        description: 'Source branch in the caller repo to build from'
        required: true
        type: string

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout caller repo
        uses: actions/checkout@v4
        with:
          ref: ${{ inputs.branch }}

      - name: Checkout smart-html scripts
        uses: actions/checkout@v4
        with:
          repository: WorldHealthOrganization/smart-html
          path: smart-html
          sparse-checkout: |
            scripts/
          sparse-checkout-cone-mode: false

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Set up Java (for publisher.jar)
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r smart-html/scripts/requirements.txt || true

      - name: Build IG using release-ui.py
        run: |
          python smart-html/scripts/release-ui.py \
            --config smart-html/scripts/release-config.yaml

      - name: Deploy webroot to gh-pages/sitepreview
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git fetch origin gh-pages || git checkout --orphan gh-pages
          git checkout gh-pages
          mkdir -p sitepreview
          rsync -av --delete webroot/ sitepreview/
          git add sitepreview
          git commit -m "Update sitepreview from branch ${{ inputs.branch }}" || echo "No changes to commit"
          git push origin gh-pages
