name: IG Release to gh-pages/sitepreview

on:
  workflow_call:
    inputs:
      sitepreview_dir:
        default: "sitepreview"
        description: "Folder under gh-pages for build output"
      java-version:
        default: "17"
        description: "Java version"
      python-version:
        default: "3.11"
        description: "Python version"

permissions:
  contents: write

jobs:
  build-and-publish:
    runs-on: ubuntu-latest

    steps:
      # Checkout caller repo (IG source)
      - name: Checkout caller repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      # If caller repo doesn't have its own release-config.yaml, use global one
      - name: Use global release-config.yaml if not overridden
        run: |
          if [ ! -f "release-config.yaml" ]; then
            cp "${{ github.action_path }}/release-config.yaml" release-config.yaml
            echo "Using global release-config.yaml from smart-html"
          else
            echo "Using repo-specific release-config.yaml"
          fi

      # Setup Java
      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: ${{ inputs.java-version }}

      # Setup Python
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ inputs.python-version }}

      # Install Python dependencies
      - name: Install Python deps
        run: |
          python -m pip install --upgrade pip
          pip install gitpython pyyaml

      # Run Python build script from smart-html
      - name: Build IG to local webroot (no push)
        run: |
          mkdir -p webroot-local
          python "${{ github.action_path }}/release-ui.py" \
            --source "${{ github.workspace }}" \
            --webroot-repo "file://$PWD/webroot-local" \
            --webroot-branch "main"

      # Checkout gh-pages branch of caller repo
      - name: Checkout gh-pages branch
        uses: actions/checkout@v4
        with:
          ref: gh-pages
          path: gh-pages
          fetch-depth: 0

      # Copy build output into sitepreview/
      - name: Copy built site into gh-pages/${{ inputs.sitepreview_dir }}
        run: |
          mkdir -p "gh-pages/${{ inputs.sitepreview_dir }}"
          rsync -a --delete webroot-local/ "gh-pages/${{ inputs.sitepreview_dir }}/"

      # Commit & push to gh-pages
      - name: Commit and push to gh-pages
        run: |
          cd gh-pages
          git config user.name  "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add "${{ inputs.sitepreview_dir }}"
          if ! git diff --cached --quiet; then
            git commit -m "Update ${{ inputs.sitepreview_dir }} from ${GITHUB_REF##*/} @ ${GITHUB_SHA::7}"
            git push origin gh-pages
          else
            echo "No changes to commit."
          fi
